version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
  backend:
    build: ./backend_experimental
    ports:
      - "5001:5001"

# docker-compose build
# docker-compose up
# docker-compose up --build